version: '3'

services:
  db:
    container_name: desafio_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: desafio
    stdin_open: true 
    tty: true
    ports:
      - 3306:3306
    